# Generated by Django 4.2.7 on 2026-04-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('order_type', models.CharField(choices=[('shop', 'Commande Boutique'), ('pressing', 'Commande Pressing'), ('fai', 'Abonnement Internet')], max_length=15)),
                ('order_id', models.CharField(help_text='ID de la commande source (CMD-xxx, PRS-xxx, etc.)', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=15)),
                ('operator', models.CharField(blank=True, choices=[('tmoney', 'T-Money'), ('flooz', 'Flooz'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('success', 'Réussi'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=15)),
                ('external_ref', models.CharField(blank=True, help_text='Référence retour opérateur', max_length=200)),
                ('receipt_url', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='initiated, callback_received, verified, failed', max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment')),
            ],
            options={
                'db_table': 'transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_type', 'order_id'], name='payments_order_t_6fa6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
    ]
