# Generated by Django 4.2.7 on 2026-04-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('current_status', models.CharField(choices=[('preparing', 'Préparation en cours'), ('ready', 'Prêt pour envoi'), ('picked_up', 'Collecté par livreur'), ('in_transit', 'En transit'), ('nearby', 'Proche de la destination'), ('delivered', 'Livré'), ('failed', 'Échec de livraison')], default='preparing', max_length=15)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tracking', to='shop.order')),
            ],
            options={
                'verbose_name': 'Suivi de livraison',
                'verbose_name_plural': 'Suivis de livraison',
                'db_table': 'delivery_tracking',
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Préparation en cours'), ('ready', 'Prêt pour envoi'), ('picked_up', 'Collecté par livreur'), ('in_transit', 'En transit'), ('nearby', 'Proche de la destination'), ('delivered', 'Livré'), ('failed', 'Échec de livraison')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.deliverytracking')),
            ],
            options={
                'db_table': 'delivery_events',
                'ordering': ['created_at'],
            },
        ),
    ]
