# Generated by Django 4.2.7 on 2026-04-20 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de prise en charge'), ('picked_up', 'Récupéré'), ('in_progress', 'En cours de traitement'), ('ready', 'Prêt'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Date de prise en charge souhaitée', null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Poids total en kg', max_digits=6, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressing_deliveries', to='users.address')),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressing_pickups', to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pressing_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande pressing',
                'verbose_name_plural': 'Commandes pressing',
                'db_table': 'pressing_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PressingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('service_type', models.CharField(choices=[('wash', 'Lavage'), ('iron', 'Repassage'), ('dry_clean', 'Nettoyage à sec'), ('wash_iron', 'Lavage + Repassage'), ('special', 'Traitement spécial')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('turnaround_hours', models.PositiveIntegerField(default=48, help_text='Délai en heures')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pressing/services/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service pressing',
                'verbose_name_plural': 'Services pressing',
                'db_table': 'pressing_services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PressingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_description', models.CharField(help_text='Description du vêtement', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pressing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pressing.pressingorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pressing.pressingservice')),
            ],
            options={
                'db_table': 'pressing_order_items',
            },
        ),
    ]
