# Generated by Django 4.2.7 on 2026-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressingorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pressingservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
