# Generated by Django 4.2.7 on 2026-04-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0002_alter_pressingorder_total_alter_pressingservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressingorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
