# Generated by Django 4.2.7 on 2026-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0003_alter_pressingorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressingorderitem',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
