# Generated by Django 4.2.7 on 2026-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0004_alter_pressingorderitem_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressingorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pressingorder',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids total en kg', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pressingorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pressingorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pressingservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pressingservice',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
