# Generated by Django 4.2.7 on 2026-04-20 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('offer_type', models.CharField(choices=[('ftth', 'FTTH Fibre'), ('wifi', 'WiFi'), ('ticket', 'Ticket Data')], max_length=10)),
                ('speed_mbps', models.PositiveIntegerField(help_text='Débit en Mbps')),
                ('data_limit_gb', models.PositiveIntegerField(blank=True, help_text='Null = illimité', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Offre data',
                'verbose_name_plural': 'Offres data',
                'db_table': 'fai_data_offers',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du foyer', max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('quartier', models.CharField(max_length=100)),
                ('city', models.CharField(default='Lomé', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('disconnected', 'Déconnecté')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foyers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foyer',
                'verbose_name_plural': 'Foyers',
                'db_table': 'fai_foyers',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='active', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='fai.foyer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fai.dataoffer')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'db_table': 'fai_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_eq', models.CharField(choices=[('olt', 'OLT'), ('onu', 'ONU'), ('splitter', 'Splitter'), ('cable', 'Câble fibre'), ('other', 'Autre')], max_length=15, verbose_name='Type')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('installed', 'Installé'), ('stock', 'En stock'), (' defective', 'Défectueux'), ('replaced', 'Remplacé')], default='stock', max_length=15)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('foyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='fai.foyer')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'fai_equipements',
            },
        ),
    ]
